from pathlib import Path


def rep(path, old, new):
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f'missing anchor in {path}: {old[:100]!r}')
    p.write_text(text.replace(old, new, 1))

core = 'src/tabletop-core.js'
rep(core, 'export const TABLE_OS_SCHEMA_VERSION = 6;', 'export const TABLE_OS_SCHEMA_VERSION = 7;')
rep(core, 'export const USER_TEMPLATE_VERSION = 5;', 'export const USER_TEMPLATE_VERSION = 6;')
rep(core, "  return { fields, values };\n}", "  return { fields, values, rankingMode: source.rankingMode === 'lowest' ? 'lowest' : 'highest' };\n}")
rep(core, "    scoreSheet: { fields: [], values: {} },", "    scoreSheet: { fields: [], values: {}, rankingMode: 'highest' },")
rep(core, "  state.scoreSheet = { fields: [], values: {} };", "  state.scoreSheet = { fields: [], values: {}, rankingMode: 'highest' };")
rep(core,
    "export function addScoreSheetField(state, { name = 'Field', key = '', kind = 'manual', formula = '', step = 1, effect = 1, includeInTotal = true } = {}) {",
    "export function setScoreRankingMode(state, mode = 'highest') {\n  const next = mode === 'lowest' ? 'lowest' : 'highest';\n  if (state.scoreSheet.rankingMode === next) return false;\n  state.scoreSheet.rankingMode = next;\n  touch(state);\n  return true;\n}\n\nexport function addScoreSheetField(state, { name = 'Field', key = '', kind = 'manual', formula = '', step = 1, effect = 1, includeInTotal = true } = {}) {")
rep(core,
    "  return { values, variables, total: Math.round(total * 100) / 100, errors };\n}\n\nexport function addCampaignFlag",
    "  return { values, variables, total: Math.round(total * 100) / 100, errors };\n}\n\nexport function scoreStandings(state) {\n  const mode = state.scoreSheet.rankingMode === 'lowest' ? 'lowest' : 'highest';\n  const includedFormulaIds = new Set(state.scoreSheet.fields.filter(field => field.kind === 'formula' && field.includeInTotal).map(field => field.id));\n  const rows = state.participants.map((participant, originalIndex) => {\n    const card = scoreCardForParticipant(state, participant.id);\n    const invalid = Object.keys(card.errors || {}).some(fieldId => includedFormulaIds.has(fieldId));\n    return { participantId: participant.id, name: participant.name, color: participant.color, total: card.total, invalid, rank: null, tied: false, originalIndex };\n  });\n  const valid = rows.filter(row => !row.invalid).sort((a, b) => {\n    const scoreOrder = mode === 'lowest' ? a.total - b.total : b.total - a.total;\n    return scoreOrder || a.originalIndex - b.originalIndex;\n  });\n  const counts = new Map();\n  valid.forEach(row => counts.set(row.total, (counts.get(row.total) || 0) + 1));\n  let previousTotal = null;\n  let previousRank = 0;\n  valid.forEach((row, index) => {\n    row.rank = index > 0 && row.total === previousTotal ? previousRank : index + 1;\n    row.tied = (counts.get(row.total) || 0) > 1;\n    previousTotal = row.total;\n    previousRank = row.rank;\n  });\n  const invalid = rows.filter(row => row.invalid).sort((a, b) => a.originalIndex - b.originalIndex);\n  return [...valid, ...invalid].map(({ originalIndex, ...row }) => row);\n}\n\nexport function addCampaignFlag")
rep(core, "    scoreFields: scoreSource.slice(0, MAX_SCORE_FIELDS).map((field, index) => {", "    rankingMode: source.rankingMode === 'lowest' ? 'lowest' : 'highest',\n    scoreFields: scoreSource.slice(0, MAX_SCORE_FIELDS).map((field, index) => {")
rep(core, "    entities: state.entities,\n    scoreFields: state.scoreSheet.fields,", "    entities: state.entities,\n    rankingMode: state.scoreSheet.rankingMode,\n    scoreFields: state.scoreSheet.fields,")
rep(core, "  state.scoreSheet.fields = template.scoreFields.map((field, index) => scoreFieldFromTemplate(field, index, usedKeys));", "  state.scoreSheet.fields = template.scoreFields.map((field, index) => scoreFieldFromTemplate(field, index, usedKeys));\n  state.scoreSheet.rankingMode = template.rankingMode;")
rep(core, "  }, index, usedKeys));\n  for (let index = 0; index < Math.min(MAX_TEAMS, template.teams || 0); index += 1) {", "  }, index, usedKeys));\n  state.scoreSheet.rankingMode = template.rankingMode === 'lowest' ? 'lowest' : 'highest';\n  for (let index = 0; index < Math.min(MAX_TEAMS, template.teams || 0); index += 1) {")

ui = 'src/tabletop.js'
rep(ui, "  addScoreSheetField, setScoreSheetFieldKey, removeScoreSheetField, setScoreSheetValue, scoreCardForParticipant,", "  addScoreSheetField, setScoreSheetFieldKey, removeScoreSheetField, setScoreSheetValue, setScoreRankingMode, scoreCardForParticipant, scoreStandings,")
rep(ui, "    addScoreField: '添加计分栏', addFormula: '添加公式栏', fieldName: '栏位', key: '变量', formula: '公式', effect: '计入', total: '总分', included: '计入总分', excluded: '仅显示',", "    addScoreField: '添加计分栏', addFormula: '添加公式栏', fieldName: '栏位', key: '变量', formula: '公式', effect: '计入', total: '总分', included: '计入总分', excluded: '仅显示',\n    scoreRanking: '排名方式', highestTotal: '高分优先', lowestTotal: '低分优先', standings: '当前排名', tied: '并列', unranked: '待修正', rankingFormulaError: '存在影响总分的无效公式，修正后再参与排名。',")
rep(ui, "    addScoreField: 'Add score field', addFormula: 'Add formula', fieldName: 'Field', key: 'Variable', formula: 'Formula', effect: 'Effect', total: 'Total', included: 'Included', excluded: 'Display only',", "    addScoreField: 'Add score field', addFormula: 'Add formula', fieldName: 'Field', key: 'Variable', formula: 'Formula', effect: 'Effect', total: 'Total', included: 'Included', excluded: 'Display only',\n    scoreRanking: 'Ranking mode', highestTotal: 'Highest total first', lowestTotal: 'Lowest total first', standings: 'Standings', tied: 'Tie', unranked: 'Fix score', rankingFormulaError: 'An invalid formula affects the total. Fix it before this player is ranked.',")
standings_fn = '''function renderScoreStandings() {
  if (!state.participants.length || !state.scoreSheet.fields.length) return '';
  const rows = scoreStandings(state);
  const mode = state.scoreSheet.rankingMode === 'lowest' ? tr('lowestTotal') : tr('highestTotal');
  return `<div class="tableos-score-standings" data-os-score-standings><div class="tableos-score-standings-head"><strong>${esc(tr('standings'))}</strong><span>${esc(mode)}</span></div><div class="tableos-score-standings-list">${rows.map(row => `<div class="${row.invalid ? 'invalid' : ''}" data-os-score-rank="${row.participantId}" data-rank="${row.rank ?? ''}"${row.invalid ? ` title="${attr(tr('rankingFormulaError'))}"` : ''}><b>${row.invalid ? '—' : `#${row.rank}`}</b><span>${esc(row.name)}</span>${row.tied && !row.invalid ? `<small>${esc(tr('tied'))}</small>` : ''}<strong>${row.invalid ? esc(tr('unranked')) : row.total}</strong></div>`).join('')}</div></div>`;
}

'''
rep(ui, 'function renderScoreSheet() {', standings_fn + 'function renderScoreSheet() {')
rep(ui, "    ${state.ui.mode === 'edit' ? `<p class=\"tableos-help\">${esc(tr('formulaHelp'))}</p>", "    ${state.ui.mode === 'edit' ? `<label class=\"tableos-score-ranking-config\"><span>${esc(tr('scoreRanking'))}</span><select data-os-score-ranking><option value=\"highest\" ${state.scoreSheet.rankingMode !== 'lowest' ? 'selected' : ''}>${esc(tr('highestTotal'))}</option><option value=\"lowest\" ${state.scoreSheet.rankingMode === 'lowest' ? 'selected' : ''}>${esc(tr('lowestTotal'))}</option></select></label><p class=\"tableos-help\">${esc(tr('formulaHelp'))}</p>")
rep(ui, "    ${state.participants.length && state.scoreSheet.fields.length ? `<div class=\"tableos-score-table\">", "    ${renderScoreStandings()}\n    ${state.participants.length && state.scoreSheet.fields.length ? `<div class=\"tableos-score-table\">")
rep(ui, "    if (d.osScoreName) { mutateScoreField(d.osScoreName, { name: element.value.trim().slice(0, 28) || tr('customField') }); saveAndRender(); return; }", "    if (d.osScoreRanking !== undefined) { setScoreRankingMode(state, element.value); persist(); render(); return; }\n    if (d.osScoreName) { mutateScoreField(d.osScoreName, { name: element.value.trim().slice(0, 28) || tr('customField') }); saveAndRender(); return; }")

css = 'src/tabletop.css'
rep(css, '.tableos-score-table { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 9px; }', '''.tableos-score-ranking-config { display: grid; grid-template-columns: minmax(110px, auto) minmax(180px, 280px); gap: 8px; align-items: center; margin-bottom: 12px; color: #94a3b8; font-size: 12px; font-weight: 700; }
.tableos-score-standings { margin: 4px 0 14px; padding: 10px; border-radius: 12px; background: rgba(2, 6, 23, .3); border: 1px solid rgba(148, 163, 184, .12); }
.tableos-score-standings-head { display: flex; justify-content: space-between; gap: 10px; margin-bottom: 7px; color: #94a3b8; font-size: 12px; }
.tableos-score-standings-list { display: grid; gap: 5px; }
.tableos-score-standings-list > div { display: grid; grid-template-columns: 42px minmax(0, 1fr) auto auto; gap: 8px; align-items: center; min-height: 38px; padding: 6px 8px; border-radius: 9px; background: #0f172a; }
.tableos-score-standings-list b { color: #5eead4; }
.tableos-score-standings-list small { color: #fbbf24; font-weight: 800; }
.tableos-score-standings-list > div > strong { text-align: right; }
.tableos-score-standings-list > div.invalid { opacity: .7; }
.tableos-score-standings-list > div.invalid b, .tableos-score-standings-list > div.invalid > strong { color: #fca5a5; }
.tableos-score-table { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 9px; }''')

test_file = 'tests/unit/tabletop-core.test.js'
rep(test_file, "  addScoreSheetField, setScoreSheetValue, evaluateFormula, scoreCardForParticipant,", "  addScoreSheetField, setScoreSheetValue, setScoreRankingMode, evaluateFormula, scoreCardForParticipant, scoreStandings,")
rep(test_file, "  const saved = createUserTemplateFromState(state, 'Friday setup');", "  setScoreRankingMode(state, 'lowest');\n  const saved = createUserTemplateFromState(state, 'Friday setup');")
rep(test_file, "  assert.equal(saved.name, 'Friday setup');", "  assert.equal(saved.name, 'Friday setup');\n  assert.equal(saved.rankingMode, 'lowest', 'ranking direction is reusable score configuration');")
rep(test_file, "  assert.deepEqual(target.scoreSheet.values, {});", "  assert.deepEqual(target.scoreSheet.values, {});\n  assert.equal(target.scoreSheet.rankingMode, 'lowest', 'My Template restores ranking direction without live scores');")
with Path(test_file).open('a') as f:
    f.write('''\n\ntest('score standings support high/low totals, competition ties and invalid-total exclusion', () => {\n  const state = createDefaultTableOsState();\n  const a = addParticipant(state, 'A'); const b = addParticipant(state, 'B'); const c = addParticipant(state, 'C'); const d = addParticipant(state, 'D');\n  const points = addScoreSheetField(state, { name: 'Points', key: 'points' });\n  [[a, 10], [b, 5], [c, 5], [d, 8]].forEach(([player, value]) => setScoreSheetValue(state, player.id, points.id, value));\n  assert.deepEqual(scoreStandings(state).map(row => [row.name, row.total, row.rank, row.tied]), [['A',10,1,false],['D',8,2,false],['B',5,3,true],['C',5,3,true]]);\n  setScoreRankingMode(state, 'lowest');\n  assert.deepEqual(scoreStandings(state).map(row => [row.name, row.total, row.rank, row.tied]), [['B',5,1,true],['C',5,1,true],['D',8,3,false],['A',10,4,false]]);\n  const divisor = addScoreSheetField(state, { name: 'Divisor', key: 'divisor', includeInTotal: false });\n  addScoreSheetField(state, { name: 'Ratio', key: 'ratio', kind: 'formula', formula: '10 / divisor', includeInTotal: true });\n  [[a,2],[b,0],[c,5],[d,2]].forEach(([player, value]) => setScoreSheetValue(state, player.id, divisor.id, value));\n  const rows = scoreStandings(state);\n  assert.equal(rows.at(-1).name, 'B');\n  assert.equal(rows.at(-1).invalid, true);\n  assert.equal(rows.at(-1).rank, null);\n});\n''')

e2e = 'tests/e2e/run-table-os-e2e.js'
rep(e2e, "  assert.equal(await firstScoreCard.locator('output').last().textContent(), '13');", "  assert.equal(await firstScoreCard.locator('output').last().textContent(), '13');\n  const highStandings = page.locator('[data-os-score-rank]');\n  assert.equal(await highStandings.first().getAttribute('data-rank'), '1', 'highest-total mode ranks the leading score first');\n  await editMode(page);\n  await page.getByRole('button', { name: '计分表', exact: true }).click();\n  await page.locator('[data-os-score-ranking]').selectOption('lowest');\n  await page.getByRole('button', { name: '牌局模式' }).click();\n  await page.getByRole('button', { name: '计分表', exact: true }).click();\n  const lowStandings = page.locator('[data-os-score-rank]');\n  assert.deepEqual(await lowStandings.evaluateAll(rows => rows.map(row => row.getAttribute('data-rank'))), ['1', '1', '1', '4'], 'lowest-total mode uses shared competition ranks for ties');\n  assert.equal(await lowStandings.first().getByText('并列', { exact: true }).count(), 1, 'tied leaders are explicitly labeled');")
rep(e2e, "  assert.match(await formulaWarning.getAttribute('title'), /公式无效/, 'formula warning explains the invalid configuration');", "  assert.match(await formulaWarning.getAttribute('title'), /公式无效/, 'formula warning explains the invalid configuration');\n  assert.equal(await page.locator('[data-os-score-rank]').first().getAttribute('data-rank'), '', 'invalid included formulas do not produce a misleading rank');")
rep(e2e, "'formula score sheet', 'unary formula operators'", "'formula score sheet', 'score standings and ties', 'unary formula operators'")

doc = 'docs/TABLE_OS_TEST_MATRIX.md'
rep(doc, "- ScoreSheet variable keys must remain formula-safe and unique; renaming a variable must migrate exact formula references so configuration edits cannot silently change scores.\n", "- ScoreSheet variable keys must remain formula-safe and unique; renaming a variable must migrate exact formula references so configuration edits cannot silently change scores.\n- Score standings must respect the configured highest/lowest-total direction, use explicit shared ranks for ties, and never rank a participant whose included total depends on an invalid formula.\n")
with Path(doc).open('a') as f:
    f.write('''\n\n### Score standings semantics\n\n- Unit: highest-total and lowest-total modes sort deterministically; equal totals use competition ranking (`1, 1, 3`) and expose tie state.\n- Unit/correctness: an invalid formula only blocks ranking when it contributes to total; affected participants stay visible but unranked instead of receiving a plausible false position.\n- Unit/template: ranking direction normalizes safely from older states and is reusable My Template structure without copying live scores.\n- Chromium: Edit setup switches ranking direction, Play mode renders tied low-score leaders explicitly, and invalid included formulas remove misleading ranks until corrected.\n''')
